// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABUtos1NwnovkZovSiElB8nU8R9VuYjSc',
    appId: '1:874191291104:web:ed565d25df661cdc454685',
    messagingSenderId: '874191291104',
    projectId: 'counting-and-sequencing-fa19c',
    authDomain: 'counting-and-sequencing-fa19c.firebaseapp.com',
    storageBucket: 'counting-and-sequencing-fa19c.firebasestorage.app',
    measurementId: 'G-HMNMV72599',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfSer4nC4y1V5QUF3BlJUWkwpKZjVo0xY',
    appId: '1:874191291104:android:b326e7b61c1456ec454685',
    messagingSenderId: '874191291104',
    projectId: 'counting-and-sequencing-fa19c',
    storageBucket: 'counting-and-sequencing-fa19c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF4FUAIqNKJCIDSttyH_rwF3iHMFEqz3Y',
    appId: '1:874191291104:ios:f7dec86df706ff9c454685',
    messagingSenderId: '874191291104',
    projectId: 'counting-and-sequencing-fa19c',
    storageBucket: 'counting-and-sequencing-fa19c.firebasestorage.app',
    iosBundleId: 'com.example.countingAndSequencing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF4FUAIqNKJCIDSttyH_rwF3iHMFEqz3Y',
    appId: '1:874191291104:ios:f7dec86df706ff9c454685',
    messagingSenderId: '874191291104',
    projectId: 'counting-and-sequencing-fa19c',
    storageBucket: 'counting-and-sequencing-fa19c.firebasestorage.app',
    iosBundleId: 'com.example.countingAndSequencing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABUtos1NwnovkZovSiElB8nU8R9VuYjSc',
    appId: '1:874191291104:web:a016750f22c2e203454685',
    messagingSenderId: '874191291104',
    projectId: 'counting-and-sequencing-fa19c',
    authDomain: 'counting-and-sequencing-fa19c.firebaseapp.com',
    storageBucket: 'counting-and-sequencing-fa19c.firebasestorage.app',
    measurementId: 'G-TVG7697MCB',
  );
}
